// Native React Native side of the map bridge. Wraps a WebView hosting
// MapLibre GL JS (mobile/assets/map.html) and exposes an imperative
// API to the rest of the app.
//
// Responsibilities:
//   - Inline the bundled map.html into the WebView (no network hop).
//   - Implement the v2 handshake: queue messages until MAP_READY, then
//     send INIT, then queue further messages until MAP_INITIALIZED.
//   - Stamp `seq` at flush time (not enqueue time) so ordering after
//     reload is correct.
//   - Detect process death (iOS onContentProcessDidTerminate, Android
//     onRenderProcessGone) and post-resume staleness via heartbeat;
//     reload + re-handshake as needed.

import React, {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';
import { AppState, type AppStateStatus, StyleSheet, View } from 'react-native';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';
import type {
  MapPin,
  MapToNative,
  NativeToMap,
} from '../map/bridge-protocol';
import { Outbox, type UnstampedMessage } from '../map/outbox';

// ---------------------------------------------------------------------
// HTML SOURCE
// ---------------------------------------------------------------------
//
// We could inline via Asset.fromModule + readAsString at runtime, but
// that's async and would gate first paint of the map on a file read.
// Instead we use require() with a Metro asset transformer-friendly
// import. The build-map-html.ts script writes the file synchronously
// into the bundle.
//
// In test environments (jest) the require() won't resolve to a real
// file; tests pass an empty/fake HTML in via prop override. The
// production path uses the bundled string from a pre-built JSON wrapper.

// Lazy-loaded so unit tests don't crash on missing bundle.
function loadBundledHtml(): string {
  try {
    // Resolve relative to this file. Metro doesn't natively bundle
    // .html — but expo-asset + expo-file-system can read it on device.
    // Simplest portable approach: a sibling .ts module exports the
    // string, generated by the build script. We try that first.

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const mod = require('../map/map-html.bundle');
    if (mod && typeof mod.default === 'string') return mod.default;
    if (mod && typeof mod.html === 'string') return mod.html;
  } catch {
    // fall through
  }
  // Fallback: empty document. The WebView will still mount but will
  // not load the map. In production, build-map-html generates the
  // bundle before metro packs the JS.
  return '<!doctype html><html><body><div id="map"></div></body></html>';
}

// ---------------------------------------------------------------------
// PUBLIC API
// ---------------------------------------------------------------------
export interface MapWebViewProps {
  /** Optional override for the inlined HTML — used by tests. */
  htmlOverride?: string;
  /** Called when a pin is tapped on the map. */
  onPinTap?: (destId: string) => void;
  /** Called when the map reports a tile fetch error. */
  onTileError?: (info: { sourceId: string; status?: number; url: string }) => void;
  /** Called when the map reports a fatal error (e.g. webgl-context-lost). */
  onMapError?: (info: { code: string; message: string }) => void;
  /** Background color shown around the WebView while it loads. */
  backgroundColor?: string;
}

export interface MapWebViewHandle {
  /** Mounts the map. Native calls this once after MAP_READY. */
  setHub: (
    hubId: string,
    center: { lat: number; lon: number; name: string },
    pins: MapPin[],
    opts?: { styleUrl?: string; isDarkMode?: boolean },
  ) => void;
  setPins: (hubId: string, pins: MapPin[]) => void;
  flyTo: (destId: string) => void;
  setSelected: (destId: string | null) => void;
  setStyle: (styleUrl: string, isDarkMode: boolean) => void;
  forceReload: () => void;
  /** Returns a promise that resolves when ACK arrives, rejects on timeout. */
  heartbeat: (timeoutMs?: number) => Promise<void>;
}

// ---------------------------------------------------------------------
// IMPLEMENTATION
// ---------------------------------------------------------------------
const DEFAULT_STYLE_URL = 'https://tiles.openfreemap.org/styles/positron';
const DEFAULT_STYLE_URL_DARK = 'https://tiles.openfreemap.org/styles/dark';

// Helper exported for tests.
export function isOutboxMessage(value: unknown): value is UnstampedMessage {
  return Boolean(value) && typeof value === 'object' && 'type' in (value as object);
}

interface InternalState {
  hubId: string | null;
  center: { lat: number; lon: number; name: string } | null;
  pins: MapPin[];
  selectedId: string | null;
  styleUrl: string;
  isDarkMode: boolean;
}

export const MapWebView = forwardRef<MapWebViewHandle, MapWebViewProps>(
  function MapWebView(props, ref) {
    const webViewRef = useRef<WebView | null>(null);
    const html = useMemo(
      () => props.htmlOverride ?? loadBundledHtml(),
      [props.htmlOverride],
    );

    // Heartbeat state.
    const pendingHeartbeats = useRef<Map<string, { resolve: () => void; reject: (e: Error) => void; timer: ReturnType<typeof setTimeout> }>>(new Map());
    const lastBackgroundedRef = useRef(false);

    // Persisted snapshot — used to re-INIT/re-SET_PINS after any reload.
    const snapshotRef = useRef<InternalState>({
      hubId: null,
      center: null,
      pins: [],
      selectedId: null,
      styleUrl: DEFAULT_STYLE_URL,
      isDarkMode: false,
    });

    // Force re-mount of the WebView. Bumping this remounts cleanly,
    // which is the most reliable way to clear any zombie JS state.
    const [reloadKey, setReloadKey] = useState(0);

    // -----------------------------------------------------------------
    // SEND / FLUSH
    // -----------------------------------------------------------------
    const sendImmediate = useCallback((msg: NativeToMap) => {
      const wv = webViewRef.current;
      if (!wv) return;
      // Double-stringify so the inner JSON becomes a JS string literal
      // with all escapes (incl. U+2028/U+2029, backslashes, quotes)
      // handled correctly by the JS parser. Trailing `;true;` dodges a
      // WKWebView bug where a non-string return hangs the bridge.
      const js = `window.handleNativeMessage(${JSON.stringify(JSON.stringify(msg))});true;`;
      wv.injectJavaScript(js);
    }, []);

    // Outbox owns the queue, seq counter, and flush gating. We pass a
    // `send` callback that injects JS into the WebView. sendImmediate
    // is closed over at construction; since it itself reads
    // webViewRef.current at call time, there is no stale-closure issue.
    const outboxRef = useRef<Outbox | null>(null);
    if (!outboxRef.current) {
      outboxRef.current = new Outbox({ send: (msg) => sendImmediate(msg) });
    }

    const enqueue = useCallback((msg: UnstampedMessage) => {
      outboxRef.current?.enqueue(msg);
    }, []);

    // -----------------------------------------------------------------
    // PROCESS-DEATH / RELOAD
    //
    // forceReload is declared up front because handleMessage references
    // it (MAP_ERROR with code webgl-context-lost triggers a reload).
    // ALWAYS bumps reloadKey: a fresh React mount guarantees a fresh JS
    // context (Android's .reload() may not re-execute inlined scripts
    // when cacheEnabled is true, and even with it off remounting is the
    // most reliable path).
    // -----------------------------------------------------------------
    const forceReload = useCallback(() => {
      outboxRef.current?.reset();
      for (const [, p] of pendingHeartbeats.current) {
        clearTimeout(p.timer);
        try { p.reject(new Error('webview reloaded')); } catch { /* ignore */ }
      }
      pendingHeartbeats.current.clear();
      setReloadKey((k) => k + 1);
    }, []);

    // Single source of INIT. Called from MAP_READY (replay snapshot)
    // and from setHub (when user picks a hub). One code path, no
    // duplicate INITs after a process-death reload.
    const enqueueInitFromSnapshot = useCallback(() => {
      const snap = snapshotRef.current;
      if (!snap.hubId || !snap.center) return;
      outboxRef.current?.enqueue({
        type: 'INIT',
        center: snap.center,
        styleUrl: snap.styleUrl,
        isDarkMode: snap.isDarkMode,
      });
    }, []);

    const handleProcessDeath = useCallback(() => {
      // eslint-disable-next-line no-console
      console.warn('[map] webview process died — reloading');
      forceReload();
    }, [forceReload]);

    // -----------------------------------------------------------------
    // MESSAGE HANDLER (Map → Native)
    // -----------------------------------------------------------------
    const handleMessage = useCallback(
      (event: WebViewMessageEvent) => {
        let parsed: MapToNative | null = null;
        try {
          parsed = JSON.parse(event.nativeEvent.data) as MapToNative;
        } catch {
          return;
        }
        if (!parsed || typeof parsed !== 'object' || !('type' in parsed)) return;
        if (typeof (parsed as { type: unknown }).type !== 'string') return;

        switch (parsed.type) {
          case 'MAP_READY': {
            // Single INIT path: replay from snapshot if we have a hub.
            enqueueInitFromSnapshot();
            outboxRef.current?.onMapReady();
            return;
          }
          case 'MAP_INITIALIZED': {
            // Replay snapshot: SET_PINS (current hub) + SET_SELECTED.
            const snap = snapshotRef.current;
            if (snap.hubId) {
              outboxRef.current?.enqueue({ type: 'SET_PINS', hubId: snap.hubId, pins: snap.pins });
            }
            if (snap.selectedId) {
              outboxRef.current?.enqueue({ type: 'SET_SELECTED', destId: snap.selectedId });
            }
            outboxRef.current?.onMapInitialized();
            return;
          }
          case 'PIN_TAPPED': {
            if (typeof parsed.destId !== 'string') return;
            props.onPinTap?.(parsed.destId);
            return;
          }
          case 'TILE_ERROR': {
            if (typeof parsed.sourceId !== 'string' || typeof parsed.url !== 'string') return;
            props.onTileError?.({
              sourceId: parsed.sourceId,
              status: typeof parsed.status === 'number' ? parsed.status : undefined,
              url: parsed.url,
            });
            return;
          }
          case 'MAP_ERROR': {
            if (typeof parsed.code !== 'string' || typeof parsed.message !== 'string') return;
            props.onMapError?.({ code: parsed.code, message: parsed.message });
            // WebGL loss → reload + re-handshake.
            if (parsed.code === 'webgl-context-lost') {
              forceReload();
            }
            return;
          }
          case 'HEARTBEAT_ACK': {
            if (typeof parsed.nonce !== 'string') return;
            const pending = pendingHeartbeats.current.get(parsed.nonce);
            if (pending) {
              clearTimeout(pending.timer);
              pendingHeartbeats.current.delete(parsed.nonce);
              pending.resolve();
            }
            return;
          }
          case 'LOG': {
            // Surface to the native console — useful when debugging map.html.
            // eslint-disable-next-line no-console
            console.log('[map]', parsed.level, parsed.message);
            return;
          }
          default:
            // Exhaustive: ignored on purpose.
            return;
        }
      },
      [enqueueInitFromSnapshot, forceReload, props.onMapError, props.onPinTap, props.onTileError],
    );

    // -----------------------------------------------------------------
    // HEARTBEAT
    // -----------------------------------------------------------------
    const heartbeatInternal = useCallback((timeoutMs = 1500) => {
      return new Promise<void>((resolve, reject) => {
        const uuid = globalThis.crypto?.randomUUID?.();
        const nonce = uuid ?? `hb-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
        const timer = setTimeout(() => {
          pendingHeartbeats.current.delete(nonce);
          reject(new Error('heartbeat timeout'));
        }, timeoutMs);
        pendingHeartbeats.current.set(nonce, { resolve, reject, timer });
        enqueue({ type: 'HEARTBEAT', nonce });
      });
    }, [enqueue]);

    // -----------------------------------------------------------------
    // APP STATE — heartbeat after resume
    // -----------------------------------------------------------------
    const heartbeatInFlight = useRef(false);
    useEffect(() => {
      const sub = AppState.addEventListener('change', (next: AppStateStatus) => {
        if (next === 'background' || next === 'inactive') {
          lastBackgroundedRef.current = true;
          return;
        }
        if (next === 'active' && lastBackgroundedRef.current) {
          lastBackgroundedRef.current = false;
          // Skip if a previous resume's heartbeat is still pending —
          // rapid lock-screen flicker would otherwise stack overlapping
          // heartbeats whose timeouts fire after a later one ACKs.
          if (heartbeatInFlight.current) return;
          heartbeatInFlight.current = true;
          heartbeatInternal(1500)
            .catch(() => forceReload())
            .finally(() => { heartbeatInFlight.current = false; });
        }
      });
      return () => sub.remove();
    }, [forceReload, heartbeatInternal]);

    // Cleanup on unmount: clear pending timers and outbox so a mid-
    // handshake unmount doesn't leak.
    useEffect(() => {
      return () => {
        for (const [, p] of pendingHeartbeats.current) {
          clearTimeout(p.timer);
          try { p.reject(new Error('unmounted')); } catch { /* ignore */ }
        }
        pendingHeartbeats.current.clear();
        outboxRef.current?.reset();
        outboxRef.current = null;
      };
    }, []);

    // -----------------------------------------------------------------
    // IMPERATIVE HANDLE
    // -----------------------------------------------------------------
    useImperativeHandle(
      ref,
      (): MapWebViewHandle => ({
        setHub: (hubId, center, pins, opts) => {
          const styleUrl =
            opts?.styleUrl ??
            (opts?.isDarkMode ? DEFAULT_STYLE_URL_DARK : DEFAULT_STYLE_URL);
          const isDarkMode = opts?.isDarkMode ?? false;
          // Snapshot first; INIT/SET_PINS are derived from snapshot so
          // there's exactly one path that produces an INIT (this and
          // MAP_READY replay both go through enqueueInitFromSnapshot).
          snapshotRef.current = {
            hubId,
            center,
            pins,
            selectedId: null,
            styleUrl,
            isDarkMode,
          };
          enqueueInitFromSnapshot();
          outboxRef.current?.enqueue({ type: 'SET_PINS', hubId, pins });
        },
        setPins: (hubId, pins) => {
          snapshotRef.current = { ...snapshotRef.current, hubId, pins };
          enqueue({ type: 'SET_PINS', hubId, pins });
        },
        flyTo: (destId) => {
          enqueue({ type: 'FLY_TO', destId });
        },
        setSelected: (destId) => {
          snapshotRef.current = { ...snapshotRef.current, selectedId: destId };
          enqueue({ type: 'SET_SELECTED', destId });
        },
        setStyle: (styleUrl, isDarkMode) => {
          snapshotRef.current = { ...snapshotRef.current, styleUrl, isDarkMode };
          enqueue({ type: 'SET_STYLE', styleUrl, isDarkMode });
        },
        forceReload,
        heartbeat: (timeoutMs) => heartbeatInternal(timeoutMs),
      }),
      [enqueue, enqueueInitFromSnapshot, forceReload, heartbeatInternal],
    );

    // -----------------------------------------------------------------
    // RENDER
    // -----------------------------------------------------------------
    return (
      <View
        accessible={false}
        style={[styles.container, { backgroundColor: props.backgroundColor ?? '#f8fafc' }]}
      >
        <WebView
          key={reloadKey}
          ref={webViewRef}
          source={{ html, baseUrl: 'https://localhost' }}
          onMessage={handleMessage}
          onContentProcessDidTerminate={handleProcessDeath}
          onRenderProcessGone={handleProcessDeath}
          mixedContentMode="never"
          originWhitelist={['https://localhost']}
          allowFileAccessFromFileURLs={false}
          allowUniversalAccessFromFileURLs={false}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          cacheEnabled={false}
          androidLayerType="hardware"
          importantForAccessibility="no-hide-descendants"
          accessibilityIgnoresInvertColors={true}
          style={styles.webview}
        />
      </View>
    );
  },
);

const styles = StyleSheet.create({
  container: { flex: 1 },
  webview: { flex: 1, backgroundColor: 'transparent' },
});
