import type { Hub } from './types';

// The original hand-curated hub. Centered on downtown Seattle per the
// AGENTS.md §3 convention (downtown of the most-recognized city in the
// metro). Drive times are rounded to ~5 min in the UI, which absorbs
// most of the Bellevue/Redmond/Seattle anchor-point variance anyway.
export const seattleHub: Hub = {
  id: 'seattle',
  name: 'Seattle',
  center: {
    name: 'Seattle, WA',
    lat: 47.6062,
    lon: -122.3321,
  },
  destinations: [
    {
      id: 'snoqualmie-falls',
      name: 'Snoqualmie Falls',
      lat: 47.5417,
      lon: -121.8377,
      reasons_to_visit: ['waterfall', 'viewpoint'],
      blurb: '268-ft waterfall with viewing platforms and a short trail.',
    },
    {
      id: 'mt-si',
      name: 'Mt Si (North Bend)',
      lat: 47.4876,
      lon: -121.7252,
      elevation_m: 1266,
      reasons_to_visit: ['hike'],
      blurb: 'Steep day hike used as the classic Mt Rainier conditioner; 8 mi roundtrip with 3,100-ft gain to a 4,167-ft summit. Discover Pass required; lots of company on weekends.',
    },
    {
      id: 'rattlesnake-ledge',
      name: 'Rattlesnake Ledge',
      lat: 47.4338,
      lon: -121.7669,
      reasons_to_visit: ['hike', 'viewpoint'],
      blurb: 'Short hike to an exposed sandstone ledge over Rattlesnake Lake and the Cedar River watershed; 4 mi roundtrip, 1,160-ft gain. Family-friendly and crowded on weekends.',
    },
    {
      id: 'mailbox-peak',
      name: 'Mailbox Peak',
      lat: 47.4539,
      lon: -121.6728,
      elevation_m: 1464,
      reasons_to_visit: ['hike'],
      blurb: 'Steep 4,000-ft climb; old mailbox at the 4,822-ft summit.',
    },
    {
      id: 'snow-lake',
      name: 'Snow Lake (Snoqualmie Pass)',
      lat: 47.4451,
      lon: -121.4192,
      reasons_to_visit: ['hike', 'lake'],
      blurb: 'Deep cirque lake below Chair Peak, one of the closest true alpine lakes to Seattle; 7 mi roundtrip with ~1,700-ft gain over a saddle. Snow lingers into July.',
    },
    {
      id: 'franklin-falls',
      name: 'Franklin Falls',
      lat: 47.4135,
      lon: -121.443,
      reasons_to_visit: ['waterfall', 'hike'],
      blurb: '70-ft waterfall on the South Fork Snoqualmie reached by a flat 2-mi family trail; year-round, with dramatic ice formations in winter.',
    },
    {
      id: 'wallace-falls',
      name: 'Wallace Falls St Park',
      lat: 47.8686,
      lon: -121.6784,
      reasons_to_visit: ['waterfall', 'hike'],
      blurb: 'Three-tier hike past Lower, Middle, and Upper Wallace Falls — 367-ft total drop on the Skykomish, with the middle viewpoint framing the valley; 5.6 mi roundtrip, 1,300-ft gain.',
    },
    {
      id: 'bainbridge-island',
      name: 'Bainbridge Island',
      lat: 47.6262,
      lon: -122.5237,
      reasons_to_visit: ['island', 'town'],
      blurb: '35-min ferry from Pier 52 to walkable Winslow village; Bainbridge Island Museum of Art (free) by the dock and the 150-acre Bloedel Reserve gardens 15 min north.',
    },
    {
      id: 'vashon-island',
      name: 'Vashon Island',
      lat: 47.4475,
      lon: -122.4663,
      reasons_to_visit: ['island', 'farm', 'coast'],
      blurb: 'Rural Puget Sound island; farms, beaches, Point Robinson Lighthouse, and a ferry ride.',
    },
    {
      id: 'gig-harbor',
      name: 'Gig Harbor',
      lat: 47.329,
      lon: -122.583,
      reasons_to_visit: ['town', 'coast'],
      blurb: 'Working harbor town on Puget Sound; waterfront walk, boat rentals, harbor-side cafes.',
    },
    {
      id: 'mt-rainier-paradise',
      name: 'Mt Rainier Nl Park - Paradise',
      lat: 46.7853,
      lon: -121.7359,
      elevation_m: 1647,
      reasons_to_visit: ['volcano', 'viewpoint', 'hike'],
      blurb: 'Headline view of Rainier; wildflower meadows in July–August.',
    },
    {
      id: 'mt-rainier-sunrise',
      name: 'Mt Rainier Nl Park - Sunrise',
      lat: 46.9141,
      lon: -121.6423,
      elevation_m: 1950,
      reasons_to_visit: ['volcano', 'viewpoint', 'hike'],
      blurb: 'Visitor center at 6,400 ft with the closest road-up view of the Emmons Glacier on Rainier; trailhead for Burroughs Mountain and Sourdough Ridge wildflower meadows. Open early July–late September.',
    },
    {
      id: 'leavenworth',
      name: 'Leavenworth',
      lat: 47.5963,
      lon: -120.6615,
      reasons_to_visit: ['town'],
      blurb: 'Bavarian-themed town in the Cascades; shopping and river walks.',
    },
    {
      id: 'lake-wenatchee',
      name: 'Lake Wenatchee St Park',
      lat: 47.8117,
      lon: -120.739,
      reasons_to_visit: ['lake', 'paddle', 'picnic', 'fish'],
      blurb: 'Glacier-fed lake with beach, swimming, and kayaking.',
    },
    {
      id: 'deception-pass',
      name: 'Deception Pass St Park',
      lat: 48.4069,
      lon: -122.6483,
      reasons_to_visit: ['coast', 'viewpoint', 'hike'],
      blurb: 'The most-visited state park in Washington; walk the 1935 bridge 180 ft above tidal current, then hit Rosario Beach tidepools, North Beach, and forest trails on Whidbey and Fidalgo.',
    },
    {
      id: 'coupeville',
      name: 'Coupeville (Whidbey Is.)',
      lat: 48.2215,
      lon: -122.6874,
      reasons_to_visit: ['town', 'historic', 'island'],
      blurb: 'Historic waterfront village on Penn Cove; mussel lunches and galleries.',
    },
    {
      id: 'port-townsend',
      name: 'Port Townsend',
      lat: 48.117,
      lon: -122.7606,
      reasons_to_visit: ['town', 'historic', 'coast'],
      blurb: 'Only intact Victorian seaport on the West Coast (1870s–80s boom-time); National Historic Landmark district with galleries, bookshops, and views across Admiralty Inlet to Whidbey.',
    },
    {
      id: 'port-gamble',
      name: 'Port Gamble',
      lat: 47.8517,
      lon: -122.5819,
      reasons_to_visit: ['town', 'historic'],
      blurb: 'Preserved 19th-century mill town; tea house, general store, walking loop.',
    },
    {
      id: 'poulsbo',
      name: 'Poulsbo',
      lat: 47.7323,
      lon: -122.6465,
      reasons_to_visit: ['town', 'coast'],
      blurb: '"Little Norway" — Sluys bakery, waterfront park, Viking shops.',
    },
    {
      id: 'la-conner',
      name: 'La Conner',
      lat: 48.392,
      lon: -122.4963,
      reasons_to_visit: ['town'],
      blurb: 'Art town on the Swinomish Channel; 5 mi from the Skagit tulip fields.',
    },
    {
      id: 'skagit-tulips',
      name: 'Skagit Valley (Mount Vernon)',
      lat: 48.4201,
      lon: -122.3346,
      reasons_to_visit: ['garden', 'farm'],
      blurb: 'Tulip fields every April; farmland, roadside stands, festival gardens.',
    },
    {
      id: 'bellingham',
      name: 'Bellingham',
      lat: 48.7519,
      lon: -122.4787,
      reasons_to_visit: ['town', 'coast'],
      blurb: 'College town; Fairhaven historic district, Bellingham Bay trails, breweries.',
    },
    {
      id: 'birch-bay',
      name: 'Birch Bay',
      lat: 48.921,
      lon: -122.753,
      reasons_to_visit: ['coast'],
      blurb: 'Wide shallow bay with a beachfront boardwalk and state park.',
    },
    {
      id: 'hurricane-ridge',
      name: 'Hurricane Ridge (Olympic Nl Park)',
      lat: 47.9692,
      lon: -123.4972,
      elevation_m: 1598,
      reasons_to_visit: ['viewpoint', 'hike', 'ski'],
      blurb: '17-mi drive from Port Angeles to a 5,242-ft ridge with 360° views of the Olympics and Strait of Juan de Fuca; ranger-led snowshoe walks Saturday afternoons in winter, road open Fri–Mon Dec–Mar.',
    },
    {
      id: 'lake-crescent',
      name: 'Lake Crescent (Olympic Nl Park)',
      lat: 48.0614,
      lon: -123.8,
      reasons_to_visit: ['lake', 'paddle', 'historic', 'hike'],
      blurb: 'Deep glacial lake with a historic lodge, kayak rentals, Marymere Falls trail.',
    },
    {
      id: 'sequim',
      name: 'Sequim',
      lat: 48.0794,
      lon: -123.1007,
      reasons_to_visit: ['town', 'garden', 'farm'],
      blurb: 'Rain-shadow town (16 in/yr); lavender farms peak mid-July, Dungeness Valley farmland.',
    },
    {
      id: 'artist-point',
      name: 'Artist Point / Picture Lake (Mt Baker)',
      lat: 48.8467,
      lon: -121.6923,
      elevation_m: 1554,
      reasons_to_visit: ['viewpoint', 'volcano', 'hike', 'lake'],
      blurb: 'End-of-road views of Mt Baker and Mt Shuksan; Picture Lake reflection loop and short alpine trails; summer-only.',
    },
    {
      id: 'diablo-lake',
      name: 'Diablo Lake (North Cascades Nl Park)',
      lat: 48.7127,
      lon: -121.102,
      reasons_to_visit: ['viewpoint', 'lake', 'paddle'],
      blurb: 'Turquoise reservoir with a famous overlook on Hwy 20; boat tours in summer.',
    },
    {
      id: 'wenatchee',
      name: 'Wenatchee',
      lat: 47.4235,
      lon: -120.3103,
      reasons_to_visit: ['town', 'garden', 'farm'],
      blurb: 'Apple capital; Columbia River loop trail, Ohme Gardens, cider houses.',
    },
    {
      id: 'cle-elum',
      name: 'Cle Elum',
      lat: 47.1954,
      lon: -120.9384,
      reasons_to_visit: ['town'],
      blurb: 'I-90 town on the Cascade east-slope; Cle Elum Bakery (operating since 1906, original brick oven), the Coal Mines Trail to Roslyn, and trailheads into the Teanaway.',
    },
    {
      id: 'roslyn',
      name: 'Roslyn',
      lat: 47.2237,
      lon: -120.9945,
      reasons_to_visit: ['town', 'historic'],
      blurb: 'Historic coal town; filming location for Northern Exposure, cafes and cemetery tour.',
    },
    {
      id: 'ellensburg',
      name: 'Ellensburg',
      lat: 47.0013,
      lon: -120.5478,
      reasons_to_visit: ['town', 'historic'],
      blurb: 'Central Washington University town in the Kittitas Valley; the Ellensburg Rodeo (since 1923) takes over Labor Day weekend alongside the Kittitas County Fair. Historic downtown the rest of the year.',
    },
    {
      id: 'anacortes',
      name: 'Anacortes (Mt Erie / Cap Sante)',
      lat: 48.5129,
      lon: -122.6127,
      reasons_to_visit: ['town', 'coast', 'viewpoint'],
      blurb: 'Gateway to the San Juans; Washington Park drive, Mt Erie overlook, Cap Sante.',
    },
    {
      id: 'crystal-mountain',
      name: 'Crystal Mountain',
      lat: 46.9345,
      lon: -121.4751,
      elevation_m: 2136,
      reasons_to_visit: ['ski', 'viewpoint', 'hike'],
      blurb: 'Summer gondola to a Rainier-facing peak; alpine hiking, winter skiing.',
    },
    {
      id: 'mt-st-helens',
      name: 'Mt St Helens (Coldwater / SR-504)',
      lat: 46.2936,
      lon: -122.2653,
      reasons_to_visit: ['volcano', 'viewpoint', 'hike'],
      blurb: 'Coldwater Lake and Hummocks Trail on SR-504; Johnston Ridge Observatory closed until spring 2027 after a 2023 landslide.',
    },
    {
      id: 'chelan',
      name: 'Lake Chelan (south end)',
      lat: 47.8414,
      lon: -120.028,
      reasons_to_visit: ['lake', 'town', 'fish', 'paddle'],
      blurb: 'Long deep lake with resorts, vineyards, beaches, Lady of the Lake boat tours.',
    },
    {
      id: 'icicle-creek',
      name: 'Icicle Creek (Leavenworth)',
      lat: 47.5493,
      lon: -120.7847,
      reasons_to_visit: ['hike'],
      blurb: 'Canyon road with trailheads for Colchuck Lake and The Enchantments.',
    },
    {
      id: 'teanaway',
      name: 'Teanaway Community Forest (Cle Elum)',
      lat: 47.2743,
      lon: -120.8727,
      reasons_to_visit: ['hike'],
      blurb: '50,000-acre community forest north of Cle Elum, the first state-owned community forest in Washington; mountain biking, horseback trails, and wildflower meadows along the Teanaway River.',
    },
    {
      id: 'snoqualmie-pass',
      name: 'Snoqualmie Pass',
      lat: 47.3925,
      lon: -121.3993,
      elevation_m: 921,
      reasons_to_visit: ['ski', 'hike'],
      blurb: 'Four ski areas of The Summit at Snoqualmie (incl. Alpental for expert terrain) and the most lit night-skiing terrain in the U.S.; PCT and alpine-lake trailheads in summer.',
    },
    {
      id: 'dash-point-sp',
      name: 'Dash Point St Park',
      lat: 47.3203,
      lon: -122.4098,
      reasons_to_visit: ['coast', 'picnic'],
      blurb: '3,300 ft of sandy Puget Sound beach in Federal Way with 11 mi of forest trails behind; a regional skimboarding spot at low tide.',
    },
    {
      id: 'point-defiance',
      name: 'Point Defiance Park (Tacoma)',
      lat: 47.3063,
      lon: -122.5207,
      reasons_to_visit: ['zoo', 'coast', 'historic', 'garden', 'picnic'],
      blurb: 'Huge waterfront park; old-growth trails, beaches, Pagoda, rose garden, zoo.',
    },
    {
      id: 'federation-forest',
      name: 'Federation Forest St Park',
      lat: 47.1563,
      lon: -121.688,
      reasons_to_visit: ['hike'],
      blurb: 'Ancient Douglas-fir grove on the White River; interpretive trails.',
    },
    {
      id: 'kanaskat-palmer-sp',
      name: 'Kanaskat-Palmer St Park',
      lat: 47.3154,
      lon: -121.9008,
      reasons_to_visit: ['paddle', 'picnic'],
      blurb: 'Green River whitewater and old-growth campground.',
    },
    {
      id: 'chuckanut-drive',
      name: 'Chuckanut Drive / Larrabee SP',
      lat: 48.6478,
      lon: -122.4856,
      reasons_to_visit: ['coast', 'viewpoint', 'hike', 'town'],
      blurb: '21-mile cliffside SR-11 from Bow-Edison to Bellingham; Larrabee SP tidepools, Taylor Shellfish, Oyster Bar dining.',
    },
    {
      id: 'rockport-sp',
      name: 'Rockport St Park',
      lat: 48.4901,
      lon: -121.5976,
      reasons_to_visit: ['hike'],
      blurb: 'Rare unlogged old-growth grove on the Skagit River.',
    },
    {
      id: 'fort-ebey-sp',
      name: 'Fort Ebey St Park (Whidbey)',
      lat: 48.2234,
      lon: -122.7724,
      reasons_to_visit: ['coast', 'hike', 'historic'],
      blurb: 'WWII coastal-defense fort on the west bluff of Whidbey; explorable Battery 248 bunkers (bring a flashlight), paragliding launch off the parade lawn, and smallmouth bass at Lake Pondilla.',
    },
    {
      id: 'fort-worden',
      name: 'Fort Worden St Park (Port Townsend)',
      lat: 48.133,
      lon: -122.7653,
      reasons_to_visit: ['historic', 'coast', 'museum'],
      blurb: 'Historic fort, lighthouse, beaches, and summer concerts.',
    },
    {
      id: 'mt-pilchuck',
      name: 'Mt Pilchuck Lookout',
      lat: 48.0703,
      lon: -121.8157,
      elevation_m: 1644,
      reasons_to_visit: ['hike', 'viewpoint', 'historic'],
      blurb: '1921 fire lookout at ~5,300 ft with 360° views of Baker, Shuksan, Rainier, and the Olympics; 5.4 mi roundtrip with 2,300-ft gain through forest and a steep boulder field near the top.',
    },
    {
      id: 'lake-22',
      name: 'Lake 22 (Mountain Loop)',
      lat: 48.0779,
      lon: -121.7437,
      reasons_to_visit: ['hike', 'lake'],
      blurb: 'Cirque lake on the north shoulder of Mt Pilchuck, set in the Lake Twentytwo Research Natural Area (logging banned since 1947); 5.4 mi roundtrip through old-growth cedar with 1,350-ft gain.',
    },
    {
      id: 'heather-lake',
      name: 'Heather Lake (Mountain Loop)',
      lat: 48.0833,
      lon: -121.7788,
      reasons_to_visit: ['hike', 'lake'],
      blurb: 'Small alpine lake in a rocky cirque below Mt Pilchuck, reached through old-growth cedar; 4.6 mi roundtrip with 1,100-ft gain, plus a short loop around the shore.',
    },
    {
      id: 'big-four-ice-caves',
      name: 'Big Four Ice Caves Viewpoint',
      lat: 48.0608,
      lon: -121.5142,
      reasons_to_visit: ['hike', 'viewpoint'],
      blurb: 'Boardwalk to a glacier-fed cirque below Big Four Mountain; ice caves are closed (fatal collapses).',
    },
    {
      id: 'lake-serene',
      name: 'Lake Serene / Bridal Veil Falls',
      lat: 47.8069,
      lon: -121.5767,
      reasons_to_visit: ['hike', 'lake', 'waterfall'],
      blurb: 'Steep hike past a 1300-ft waterfall to a blue alpine lake.',
    },
    {
      id: 'blanca-lake',
      name: 'Blanca Lake',
      lat: 47.9908,
      lon: -121.3411,
      reasons_to_visit: ['lake', 'hike'],
      blurb: 'Turquoise glacial lake; 7.5-mi out-and-back, 3,300 ft gain.',
    },
    {
      id: 'boulder-river',
      name: 'Boulder River Trail (Darrington)',
      lat: 48.2598,
      lon: -121.7959,
      reasons_to_visit: ['hike', 'waterfall'],
      blurb: 'Easy riverside path to twin falls in an old-growth rainforest.',
    },
    {
      id: 'oyster-dome',
      name: 'Oyster Dome (Chuckanut)',
      lat: 48.6019,
      lon: -122.4358,
      reasons_to_visit: ['hike', 'viewpoint'],
      blurb: 'Cliff-top sandstone perch in Blanchard State Forest with views over Samish Bay, the San Juans, and the Olympics; 6.4 mi roundtrip with ~1,900-ft gain. Bring a headlamp for the bat caves.',
    },
    {
      id: 'tipsoo-lake',
      name: 'Tipsoo Lake (Chinook Pass)',
      lat: 46.8703,
      lon: -121.5192,
      elevation_m: 1640,
      reasons_to_visit: ['viewpoint', 'lake'],
      blurb: 'Roadside alpine lake with Rainier reflection; summer-only road.',
    },
    {
      id: 'tolmie-peak',
      name: 'Tolmie Peak (Mowich)',
      lat: 46.937,
      lon: -121.8657,
      elevation_m: 1676,
      reasons_to_visit: ['hike', 'viewpoint', 'historic'],
      blurb: 'Fire lookout hike from Mowich Lake; rough gravel access road.',
    },
    {
      id: 'naches-peak-loop',
      name: 'Naches Peak Loop',
      lat: 46.8672,
      lon: -121.5227,
      reasons_to_visit: ['hike', 'viewpoint'],
      blurb: 'Easy 3.4-mi alpine loop on the PCT around Naches Peak at Chinook Pass; lupine carpets in late July–August and a head-on Rainier view from the south side. SR-410 closes in winter.',
    },
    {
      id: 'lake-cushman',
      name: 'Lake Cushman',
      lat: 47.446,
      lon: -123.2085,
      reasons_to_visit: ['lake', 'paddle', 'fish'],
      blurb: '4,000-acre clear-water reservoir on the south Olympics, max depth ~260 ft; swimming, boating, scuba, with the Staircase entrance to Olympic NP a mile up the road.',
    },
    {
      id: 'kachess-lake',
      name: 'Kachess Lake',
      lat: 47.2828,
      lon: -121.2566,
      reasons_to_visit: ['lake', 'paddle', 'fish'],
      blurb: 'Large I-90 reservoir 5 mi west of Cle Elum Lake; 150-site Kachess Campground on the forested NW shore, kokanee fishing, swim beach.',
    },
    {
      id: 'cooper-lake',
      name: 'Cooper Lake (Salmon La Sac)',
      lat: 47.4167,
      lon: -121.1833,
      reasons_to_visit: ['lake', 'paddle'],
      blurb: 'Quiet forested lake beyond Cle Elum Lake; trailheads for Pete Lake.',
    },
    {
      id: 'cle-elum-lake',
      name: 'Cle Elum Lake',
      lat: 47.2789,
      lon: -121.0736,
      reasons_to_visit: ['lake', 'paddle'],
      blurb: 'Reservoir on the Cle Elum River 8 mi NW of town; Wish Poosh Campground and Speelyi Beach for swimming, paddleboarding, and kokanee fishing.',
    },
    {
      id: 'dungeness-spit',
      name: 'Dungeness Spit (Wildlife Refuge)',
      lat: 48.1464,
      lon: -123.1886,
      reasons_to_visit: ['wildlife', 'coast', 'historic'],
      blurb: 'Longest natural sand spit in the U.S.; 5-mi beach walk to the lighthouse, wildlife refuge birding.',
    },
    {
      id: 'point-no-point',
      name: 'Point No Point Lighthouse',
      lat: 47.9131,
      lon: -122.5285,
      reasons_to_visit: ['coast', 'historic'],
      blurb: 'Working lighthouse and wide pebble beach on the Kitsap Peninsula.',
    },
    {
      id: 'ebeys-landing',
      name: "Ebey's Landing (Whidbey)",
      lat: 48.1895,
      lon: -122.6816,
      reasons_to_visit: ['hike', 'coast', 'historic'],
      blurb: 'Prairie-to-bluff loop along Whidbey Island farmland and sea cliffs.',
    },
    {
      id: 'snohomish',
      name: 'Snohomish',
      lat: 47.9129,
      lon: -122.0982,
      reasons_to_visit: ['town'],
      blurb: 'Antique-mall row in a historic riverfront downtown; Star Center and 1st Street shops.',
    },
    {
      id: 'langley-whidbey',
      name: 'Langley (Whidbey Is.)',
      lat: 48.0395,
      lon: -122.4078,
      reasons_to_visit: ['town', 'island', 'wildlife'],
      blurb: 'Bluff-top village with galleries, bookshops, and whale watching.',
    },
    {
      id: 'stevens-pass',
      name: 'Stevens Pass',
      lat: 47.7462,
      lon: -121.0857,
      elevation_m: 1238,
      reasons_to_visit: ['ski'],
      blurb: 'Vail-owned ski area on US-2; lift-served downhill mountain biking off the Hogsback chair late June through early October — the only lift-access bike park in Washington.',
    },
    {
      id: 'twin-falls-nb',
      name: 'Twin Falls (North Bend)',
      lat: 47.4536,
      lon: -121.7133,
      reasons_to_visit: ['hike', 'waterfall'],
      blurb: 'Easy forest hike to a 150-ft waterfall along the South Fork Snoqualmie.',
    },
    {
      id: 'yakima',
      name: 'Yakima',
      lat: 46.6021,
      lon: -120.5059,
      reasons_to_visit: ['town'],
      blurb: 'Rain-shadow city in WA wine country; ~300 sunny days a year, tasting rooms, riverfront.',
    },
    {
      id: 'yakima-river-canyon',
      name: 'Yakima River Canyon (Umtanum)',
      lat: 46.8509,
      lon: -120.4812,
      reasons_to_visit: ['paddle', 'hike', 'wildlife'],
      blurb: 'Basalt canyon drive; suspension bridge and desert-river hikes.',
    },
    {
      id: 'ginkgo-petrified-forest',
      name: 'Ginkgo Petrified Forest St Park (Vantage)',
      lat: 46.9481,
      lon: -119.9928,
      reasons_to_visit: ['historic', 'museum', 'hike'],
      blurb: 'Columbia River shoreline, petrified wood trails, and basalt cliffs.',
    },
    {
      id: 'cowiche-canyon',
      name: 'Cowiche Canyon',
      lat: 46.6285,
      lon: -120.5793,
      reasons_to_visit: ['hike'],
      blurb: 'Rail-trail through basalt walls just outside Yakima; shrub-steppe.',
    },
    {
      id: 'oak-creek',
      name: 'Oak Creek Wildlife Area',
      lat: 46.7213,
      lon: -120.8197,
      reasons_to_visit: ['wildlife'],
      blurb: 'Bighorn sheep country; elk feeding station in winter.',
    },
    {
      id: 'white-pass',
      name: 'White Pass',
      lat: 46.6368,
      lon: -121.3935,
      elevation_m: 1372,
      reasons_to_visit: ['ski', 'hike'],
      blurb: 'Cascade pass south of Rainier; ski area in winter, PCT in summer.',
    },
    {
      id: 'forks-of-the-sky',
      name: 'Forks of the Sky St Park (Index)',
      lat: 47.8156,
      lon: -121.5594,
      reasons_to_visit: ['historic', 'viewpoint'],
      blurb: "Granite climbing walls (Index Town Wall) at the North/South Fork Skykomish confluence; town of Index sits in its shadow.",
    },
    {
      id: 'twanoh-sp',
      name: 'Twanoh St Park',
      lat: 47.3745,
      lon: -122.9726,
      reasons_to_visit: ['coast', 'picnic', 'paddle'],
      blurb: 'Warm Hood Canal beach with madrona forest; oysters, kayak launch, horseshoes.',
    },
    {
      id: 'penrose-point-sp',
      name: 'Penrose Point St Park',
      lat: 47.2615,
      lon: -122.7475,
      reasons_to_visit: ['coast', 'picnic'],
      blurb: 'Tidepools at low tide; forested Key Peninsula trails and a sheltered cove.',
    },
    {
      id: 'south-whidbey-sp',
      name: 'South Whidbey St Park',
      lat: 48.0375,
      lon: -122.5545,
      reasons_to_visit: ['hike', 'coast', 'island'],
      blurb: 'Old-growth loop trails and stairs down a 300-ft Puget Sound bluff to the beach.',
    },
    {
      id: 'belfair-sp',
      name: 'Belfair St Park',
      lat: 47.4289,
      lon: -122.8821,
      reasons_to_visit: ['coast', 'wildlife', 'picnic'],
      blurb: 'Wide tidal marsh at the head of Hood Canal; saltwater wading, birding, picnics.',
    },
    {
      id: 'millersylvania-sp',
      name: 'Millersylvania St Park',
      lat: 46.9097,
      lon: -122.908,
      reasons_to_visit: ['lake', 'paddle', 'picnic'],
      blurb: 'Old-growth forest around Deep Lake near Olympia; swimming, kayaking, easy trails.',
    },
    {
      id: 'scenic-beach-sp',
      name: 'Scenic Beach St Park',
      lat: 47.6406,
      lon: -122.8612,
      reasons_to_visit: ['coast', 'viewpoint', 'picnic'],
      blurb: 'Pebble beach with head-on Olympic Mountain views across Hood Canal.',
    },
    {
      id: 'olympia-capitol',
      name: 'Olympia (State Capitol)',
      lat: 47.0357,
      lon: -122.9072,
      reasons_to_visit: ['historic', 'town'],
      blurb: 'Tour the Legislative Building, loop Capitol Lake, explore the downtown waterfront.',
    },
    {
      id: 'tacoma-museums',
      name: 'Tacoma (Museum District)',
      lat: 47.2442,
      lon: -122.4379,
      reasons_to_visit: ['museum', 'town'],
      blurb: 'Museum of Glass with glassblowing demos, Chihuly Bridge, Tacoma Art Museum, waterfront walk.',
    },
    {
      id: 'padilla-bay',
      name: 'Padilla Bay Estuarine Reserve',
      lat: 48.4978,
      lon: -122.4718,
      reasons_to_visit: ['wildlife', 'coast', 'museum'],
      blurb: 'Interpretive center + shoreline trail over Skagit tideflats; excellent for birding.',
    },
    {
      id: 'nisqually-nwr',
      name: 'Nisqually Wildlife Refuge',
      lat: 47.0702,
      lon: -122.7067,
      reasons_to_visit: ['wildlife', 'coast'],
      blurb: 'Mile-long boardwalk over tidal flats; exceptional birding year-round.',
    },
    {
      id: 'friday-harbor-sjis',
      name: 'Friday Harbor (San Juan Is.)',
      lat: 48.5348,
      lon: -123.0139,
      reasons_to_visit: ['island', 'town', 'wildlife', 'coast'],
      blurb: 'Walk-on ferry from Anacortes to the main town of the San Juans; whale-watch tours, galleries, waterfront.',
    },
    {
      id: 'lime-kiln-point',
      name: 'Lime Kiln Point St Park (San Juan Is.)',
      lat: 48.5163,
      lon: -123.1517,
      reasons_to_visit: ['wildlife', 'coast', 'viewpoint', 'historic'],
      blurb: 'West-side San Juan Island lighthouse park; land-based orca viewing May–September.',
    },
    {
      id: 'maple-pass',
      name: 'Maple Pass Loop (Rainy Pass)',
      lat: 48.5161,
      lon: -120.7347,
      elevation_m: 1845,
      reasons_to_visit: ['hike', 'viewpoint', 'lake'],
      blurb: '7.2-mi ridge loop from Rainy Pass; golden larches in October, views over Rainy and Ann lakes.',
    },
    {
      id: 'washington-pass',
      name: 'Washington Pass Overlook',
      lat: 48.5264,
      lon: -120.6536,
      elevation_m: 1669,
      reasons_to_visit: ['viewpoint'],
      blurb: 'Paved 0.2-mi loop to a cliff view of Liberty Bell and the Early Winters Spires on Hwy 20.',
    },
    {
      id: 'nooksack-falls',
      name: 'Nooksack Falls',
      lat: 48.9063,
      lon: -121.8144,
      reasons_to_visit: ['waterfall'],
      blurb: 'Short walk to an 88-ft gorge waterfall off the Mt Baker Highway; viewing platforms only, no swimming.',
    },
    {
      id: 'chain-lakes-loop',
      name: 'Chain Lakes Loop (Mt Baker)',
      lat: 48.8542,
      lon: -121.7022,
      elevation_m: 1554,
      reasons_to_visit: ['hike', 'lake', 'viewpoint', 'volcano'],
      blurb: '6.5-mi alpine loop from Artist Point past Iceberg, Hayes, and Mazama lakes; Baker and Shuksan views.',
    },
    {
      id: 'heybrook-lookout',
      name: 'Heybrook Lookout (Index)',
      lat: 47.8094,
      lon: -121.5266,
      reasons_to_visit: ['hike', 'viewpoint', 'historic'],
      blurb: '2-mi climb to a climbable 1920s fire lookout above Index and the Skykomish valley on US-2.',
    },
    {
      id: 'woodinville',
      name: 'Woodinville Wine Country',
      lat: 47.7543,
      lon: -122.1215,
      reasons_to_visit: ['town'],
      blurb: '130+ tasting rooms in the Sammamish River valley; Chateau Ste Michelle anchors the district.',
    },
    {
      id: 'poo-poo-point',
      name: 'Poo Poo Point (Tiger Mtn)',
      lat: 47.5179,
      lon: -121.9838,
      reasons_to_visit: ['hike', 'viewpoint'],
      blurb: '6.9-mi climb to a paragliding launch above Issaquah; valley views, Rainier on clear days.',
    },
    {
      id: 'snoqualmie-tunnel',
      name: 'Snoqualmie Tunnel (Iron Horse)',
      lat: 47.3929,
      lon: -121.3857,
      reasons_to_visit: ['hike', 'historic'],
      blurb: '2.3-mi flat walk or bike through the longest non-motorized rail tunnel in the U.S.; open May–November.',
    },
    {
      id: 'gold-creek-pond',
      name: 'Gold Creek Pond (Snoqualmie Pass)',
      lat: 47.3921,
      lon: -121.3775,
      reasons_to_visit: ['lake', 'picnic'],
      blurb: 'Paved 1-mi loop with Cascade reflections near Snoqualmie Pass; picnic tables and wildlife viewing.',
    },
    {
      id: 'mt-walker',
      name: 'Mt Walker (Olympics)',
      lat: 47.7878,
      lon: -122.9019,
      elevation_m: 817,
      reasons_to_visit: ['viewpoint', 'hike'],
      blurb: 'Drive or 4-mi hike to twin summits above Hood Canal; Olympics one side, Seattle skyline the other.',
    },
    {
      id: 'mima-mounds',
      name: 'Mima Mounds Natural Area',
      lat: 46.903,
      lon: -123.0411,
      reasons_to_visit: ['hike', 'wildlife'],
      blurb: 'Prairie mound formations of uncertain origin south of Olympia; half-mile accessible loop, camas blooms in May.',
    },
    {
      id: 'lake-quinault',
      name: 'Lake Quinault (Olympic Nl Forest)',
      lat: 47.4606,
      lon: -123.854,
      reasons_to_visit: ['lake', 'paddle', 'historic', 'hike'],
      blurb: 'South-shore rainforest lake with the 1926 Quinault Lodge; kayak rentals and trails past record Sitka spruce.',
    },
    {
      id: 'mt-baker-ski',
      name: 'Mt Baker Ski Area / Heather Meadows',
      lat: 48.857,
      lon: -121.6785,
      elevation_m: 1280,
      reasons_to_visit: ['ski', 'hike', 'viewpoint'],
      blurb: 'World-record snowfall (1999); winter skiing at Heather Meadows, summer Table Mtn trailhead and Nordic loops.',
    },
    {
      id: 'ape-cave',
      name: 'Ape Cave (Mt St Helens)',
      lat: 46.1083,
      lon: -122.2108,
      reasons_to_visit: ['hike'],
      blurb: "2.4-mi lava tube on Mt St Helens' south flank; timed-entry pass May–Oct, headlamp required, steady 42°F inside.",
    },
    {
      id: 'orcas-island',
      name: 'Orcas Island / Mt Constitution',
      lat: 48.6786,
      lon: -122.8315,
      elevation_m: 734,
      reasons_to_visit: ['island', 'viewpoint', 'hike'],
      blurb: 'Ferry-access San Juan island; 2,409-ft Mt Constitution summit with a 1936 stone tower, Moran SP lakes, Eastsound village.',
    },
    {
      id: 'ohanapecosh-silver-falls',
      name: 'Ohanapecosh / Silver Falls (Mt Rainier)',
      lat: 46.7328,
      lon: -121.5691,
      reasons_to_visit: ['hike', 'waterfall', 'volcano'],
      blurb: 'Old-growth grove and Silver Falls loop on the Ohanapecosh River; SE corner of Mt Rainier NP via SR-123.',
    },
  ],
};
